### ISSUE TITLE
jmock.org points to 2.6.1

### ISSUE THREAD

**Issue by nmwael** [jmock-developers/jmock-library#100]
Hi Jmock fits our usecase very well, and works like we want to.. But I am having a hard time convincing collegues to use a framework that seemingly are stale.. When I go to jmock.org it points at release 2.6.1 which are from 2013, however I can see that releases have been made 2017.. Mailing lists does not work either..

So what can I do to help getting the website up to date and mailinglist up and working again?

regards Nino

**Comment by olibye** [comment]
Make changes in the https://github.com/jmock-developers/jmock-website
Project.
Build as detailed in the readme, then submit a PR targeting https://github.com/jmock-developers/jmock-library/tree/gh-pages

**Comment by olibye** [comment]
Feel free to change the mailing list address and instruction to raising Github issues.
https://github.com/jmock-developers/jmock-library/issues

Lastly you can solve outstanding issues labeled 'website'.

Please do each of these things in separate pull requests.
That would be a great help.

**Comment by olibye** [comment]
I'll leave this issue open until you've updated the website ;-)

**Comment by olibye** [comment]
I've updated jmock.org using the gh-pages branch to publish 2.9.0

**Comment by sf105** [comment]
You might be interested, @tumbarumba has just moved the website to the /docs directory, rather than the gh-pages branch. It appears to be a new setting and should be a bit easier to see.

**Comment by tumbarumba** [comment]
FYI, that was for Hamcrest (here's the relevant pull request: https://github.com/hamcrest/JavaHamcrest/pull/222)
