### ISSUE TITLE
Mockery bleed over between tests.

### ISSUE THREAD

**Issue by smccants** [jmock-developers/jmock-library#103]
Before 2.6.x you could define your Mockery in the `@Before` method of a unit test, so that you had a new Mockery for every test and there was no chance of bleed over between the tests.  The code might look something like:

```
@RunWith(JMock.class)
public class SomeTestClass {

    private Mockery context;

    @Before
    public void setUp() {
        context = new Mockery();
    }
}
```
Starting with 2.6.x, you need to define you Mockery before the `@Before` as a result of this change (https://github.com/jmock-developers/jmock-library/commit/27a0bd7e50a3cd82b26fc8ea947a65fd203088b7).  So now you often have code that looks like:

```
@RunWith(JMock.class)
public class SomeTestClass {

    public static Mockery context;

    @BeforeClass
    public static void globalSetUp() {
        context = new Mockery();
    }
}
```
However, this causes mocked objects to persist between runs of the unit test, potentially resulting in errors like:

```
a mock with name fullScreenFrame already exists
java.lang.IllegalArgumentException: a mock with name fullScreenFrame already exists
    at org.jmock.Mockery.mock(Mockery.java:128)
    at org.jmock.Mockery.mock(Mockery.java:120)
```
Wouldn't it be better to hook the `JMock.mockeryOf(Test)` code after the test has been setup (after `@Before` has been called)?

As a work around, creating the Mockery in test's constructor avoids the bleed over.  For example:
```
@RunWith(JMock.class)
public class SomeTestClass {

    private Mockery context;

    public SomeTestClass() {
         context = new Mockery();
    }
}
```
This was tested with JMock 2.8.3 and JUnit 4.11.

**Comment by smccants** [comment]
Also tried to start some discussion here: https://stackoverflow.com/questions/47719072/jmock-static-mockery-vs-local-mockery

**Comment by olibye** [comment]
Thanks for the clear write up. I'll look into it

**Comment by smccants** [comment]
A better workaround that doesn't run into this bleed over problem is to use JUnitRuleMockery.

For example:

```
public class SomeTestClass {

   @Rule
   public JUnitRuleMockery context = new JUnitRuleMockery();

   private SomeOtherClass fullScreenFrame;

   @Before
   public void setUp() {
       fullScreenFrame = context.mock(SomeOtherClass.class);
   }
}
```

This may not even be a work around, but the right way to do it.

**Comment by sf105** [comment]
Yes it is. Also, because JUnit flushes the test class each time you can set your fields on declaration as final rather than in the setup.

S

**Comment by olibye** [comment]
Yes, on second reading we always use the @Rule form
