### ISSUE TITLE
ConcurrentModificationException on Synchronised and multi-threaded unit tests

### ISSUE THREAD

**Issue by smccants** [jmock-developers/jmock-library#104]
I have been seeing an occasional ConcurrentModificationException coming from some of multi-threaded unit tests and have finally tracked it down.  It is caused by one thread adding expectations, while another thread is dispatching an expectation.  This problem has been seen with JMock 2.8.3.

Here is a simple test case to reproduce the problem:
```
import org.jmock.Expectations;
import org.jmock.auto.Mock;
import org.jmock.integration.junit4.JUnitRuleMockery;
import org.jmock.lib.concurrent.Synchroniser;
import org.junit.Rule;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.hamcrest.Matchers.*;
import static org.jmock.AbstractExpectations.returnValue;

/**
 * Testing JMock for a concurrent modification exception.
 * @author Stephen McCants
 */
public class JMockTest {
    @Mock
    private MyTestClass mock;
    
    @Rule
    public JUnitRuleMockery context = new JUnitRuleMockery(){{
        setThreadingPolicy(new Synchroniser());
    }};
    
    @Test
    public void testConncurrentModifcationException_viaAdd2() throws InterruptedException {
        // Initial expectations
        context.checking(new Expectations(){{
            allowing(mock).firstMethod(1); will(returnValue(11));
            allowing(mock).firstMethod(2); will(returnValue(12));
            allowing(mock).firstMethod(3); will(returnValue(13));
            allowing(mock).firstMethod(4); will(returnValue(14));
            allowing(mock).firstMethod(5); will(returnValue(15));
        }});
        Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {
                // Pound on things for one second
                assertThat(mock.firstMethod(5), is(15));
            }
        }, "Press our luck thread");
        thread.start();

        // Now add new expectations, while the thread is running 
        context.checking(new Expectations(){{
            oneOf(mock).secondMethod(10); will(returnValue(20));
        }});
        assertThat(mock.secondMethod(10), is(20));
        thread.join();
    }
    
    private static interface MyTestClass {
        public int firstMethod(int number);
        public int secondMethod(int number);
    }
}
```
Since it is a race condition, I cannot reliably reproduce the problem without the help of break points.  You should set the following break points:

1. InvocationDispatcher.add(Expectation) line 24
2. InvocationDispatcher.dispatch(...) line 79

Run the test under the debugger and follow these steps:
1. Resume after the first 5 adds.
2. It will now stop at both break points at the same time in two different threads.
3. Step through the dispatch method until you are inside the for loop, but have not yet found the matching expectation.
4. Step through the add function until it returns.
5. Step through the dispatch method and on the next fetch from the iterator, it will throw a ConcurrentModificationException.

Here is the resulting stack trace:

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at org.jmock.internal.InvocationDispatcher.dispatch(InvocationDispatcher.java:79)
	at org.jmock.Mockery.dispatch(Mockery.java:244)
	at org.jmock.Mockery.access$100(Mockery.java:29)
	at org.jmock.Mockery$MockObject.invoke(Mockery.java:284)
	at org.jmock.internal.InvocationDiverter.invoke(InvocationDiverter.java:27)
	at org.jmock.internal.FakeObjectMethods.invoke(FakeObjectMethods.java:38)
	at org.jmock.lib.concurrent.Synchroniser.synchroniseInvocation(Synchroniser.java:82)
	at org.jmock.lib.concurrent.Synchroniser.access$000(Synchroniser.java:23)
	at org.jmock.lib.concurrent.Synchroniser$1.invoke(Synchroniser.java:74)
	at org.jmock.lib.legacy.ClassImposteriser$4.invoke(ClassImposteriser.java:136)
	at com.hcs.bugs.JMockTest$MyTestClass$$EnhancerByCGLIB$$92142c3.firstMethod(<generated>)
	at com.hcs.bugs.JMockTest$6.run(JMockTest.java:89)
	at java.lang.Thread.run(Thread.java:745)
```

It seems there is some missing synchronization around the expectations List in InvocationDispatcher.

**Comment by olibye** [comment]
Thanks for the excellent instructions on how to reproduce. I'll have a look at this.

**Comment by olibye** [comment]
I have just reproduced this.

**Comment by olibye** [comment]
I feels odd to me to  add expectations after starting to make the test invocations. However, it's not against the rules and I can see how the Synchroniser implies this should work multi threaded.

Here are a few options I'm pulling over:
a) initialise org.jmock.internal.InvocationDispatcher.expectations with a CopyOnWriteArrayList. However this would be odd without taking the same approach with statemachines. Expensive for single threaded tests and/or tests with many expectations.
b) synchronize InvocationDispatcher.[add,dispatch,isSatisfied,newStateMachine]. Little cost to single threaded tests.

**Comment by olibye** [comment]
a) (CopyOnWriteArrayList) has the advantage of not introducing locks that could deadlock peoples tests.

I may delegate choice of expectation and statemachinne collection in the InvocationDIspatcher to the ThreadingPolicy by asking the ThreadingPolicy to build the InvocationDispatcher.

This would allow the strategy to be up to the test writer.  SingleThreaded, Synchronized already exist.  CopyOnWrite could be a new ThreadingPolicy.
