### ISSUE TITLE
[GitHub Migration] Release Process : Convert release.sh

### ISSUE THREAD

**Issue by tobyweston** [jmock-developers/jmock-library#11]
The `release.sh` script is really about building and publishing a previous tagged baseline of the software.

It's exports the tag from Subversion on Codehaus before attempting to publish the built artifacts via SCP to `jmock@www.jmock.org:/home/jmock`.

This should be updated to build the artifacts from the Github tag and deploy to Guthub pages (a [gh_pages branch](https://github.com/jmock-developers/jmock-library/tree/gh-pages) of `jmock-library`). The deploy step is really just a `git push` (which is nice).

This is required so the packaging step can download the release artefacts from `jmock.org/dist`.

**Comment by olibye** [comment]
Moved to maven
