### ISSUE TITLE
Should InvocationDispatcher be updated when ThreadingPolicy is changed?

### ISSUE THREAD

**Issue by spikeh** [jmock-developers/jmock-library#121]
At the moment, InvocationDispatcher in Mockery is marked final. So after changing ThreadingPolicy, the old dispatcher (from a SingleThreadedPolicy) continues to be used. The original dispatcher receives both added expectations and invoked invocations.

All 6 tests in org.jmock.test.unit.lib.concurrent.internal.SynchroniserTests fail.

For some reason, no tests are run in org.jmock.junit5.unit.lib.concurrent.internal.SynchroniserTests.

I'm working on an extension to jMock that is currently a fork, which is difficult to maintain and keep up to date. I'm looking at moving the extension out with jMock as a dependency instead.

**Comment by olibye** [comment]
I'll look into this

**Comment by olibye** [comment]
I'm sorry I've not had time to look at this.
I now see why junit5 tests are failing.
I'm working on a fix

**Comment by olibye** [comment]
Solve in master, released in 2.12.0-SNAPSHOT
