### ISSUE TITLE
ByteBudyImposterizer fails to mock scala case classes

### ISSUE THREAD

**Issue by laurynaslubys** [jmock-developers/jmock-library#180]
It seems, that the ByteBuddy imposterizer is too strict when mocking classes. We have the following situation: 
1. a scala case class has a field annotated with `@JsonIgnore`
2. the scala compiler adds this annotation to the parameter corresponding with the field in the scala generated `copy` method
3. ByteBuddy type validation fails, because `@JsonIngore` is not marked as being valid for parameters 

I believe that JMock should not validate the generated class as the validation is too strict and if the source class is not strictly valid according to ByteBuddy, it's impossible to mock such a class at all.  

What are your thoughts?

I'll submit a PR shortly

**Comment by olibye** [comment]
fixed by #181
