### ISSUE TITLE
Will there ever be a new release?

### ISSUE THREAD

**Issue by dpeger** [jmock-developers/jmock-library#228]
It's (again) more than 2 years since the latest release. Important issues are already fixed on master (e.g. commit https://github.com/jmock-developers/jmock-library/commit/dad8d62e1f10464ce0d36f3bcb011a1dfe86d58f).

I'm wondering if this project is now finally retired after having returned from the dead already once or if we will see some updates at some point in time? Or at least a new release with the existing changes...

@jmock-developers (@olibye, @tobyweston, @npryce, @sf105, @PASimmons)

**Comment by olibye** [comment]
https://github.com/jmock-developers/jmock-library/releases/tag/2.13.0
