### ISSUE TITLE
What happened to JIRA

### ISSUE THREAD

**Issue by tobyweston** [jmock-developers/jmock-library#58]
The old issue site has stopped working for me, ie, http://jira.codehaus.org/browse/JMOCK-256

It complains about permissions and to talk to my administrator. Is it just me?

Has it been removed? It had some valuable stuff on there (ie, it wasn't all moved over to Github)

**Comment by olibye** [comment]
Want to close this Toby?

**Comment by tobyweston** [comment]
Sure.
The specifics have mostly been recreated as [issue 36](https://github.com/jmock-developers/jmock-library/issues/36) but the general point still holds; not everything was migrated...
