### ISSUE TITLE
jmock-junit4 dependency issure

### ISSUE THREAD

**Issue by inDestiny** [jmock-developers/jmock-library#61]
when I add the dependency:
<dependency>
  <groupId>org.jmock</groupId>
  <artifactId>jmock-junit4</artifactId>
  <version>2.6.0</version>
</dependency>

it will find hamcrest-core 1.1,  but It should be hamcrest-core 1.3.

**Comment by olibye** [comment]
Solved in 2.8.0, in maven central now.
