### ISSUE TITLE
JMock 2.8.0 Package Signing

### ISSUE THREAD

**Issue by olibye** [jmock-developers/jmock-library#69]
Toby or Steve,
I've pushed JMock 2.8.0 which makes 2.7.0 into a vanilla maven project with a travis build.
Can we do a key exchange at XTC or is it enough for me to make a subkey with uid:developers@jmock.org for somebody to sign?

Oli

**Comment by sf105** [comment]
I'm not sure about the keys. I think it's pretty easy to apply for one of your own.

S
