### ISSUE TITLE
Changing the state of the mocked object

### ISSUE THREAD

**Issue by AnandMuley** [jmock-developers/jmock-library#70]
In the case of pass by reference : 
I have a UserDaoImpl class with create method having void return type. While writing the unit test case in the UserServiceImpl class I am mocking the UserDaoImpl. When I set and expectation that when the create method of the dao is called then I wanted to change the state of the mocked object as it is passed by reference and hence the Id field in the UserBean is updated. Could not find any way to achieve this in jmock. Could you please tell me is this a known issue or there is some way to achieve this.

**Comment by sf105** [comment]
it’s possible what you’re looking for is to call an Action, but it’s hard to tell without an example of the code.

S

**Comment by AnandMuley** [comment]
Thnx for the suggestion. Tried creating the Custom Action and updated the required field. Below is the sample of the custom action:

public class OrderCreateAction implements Action{

    @Override
    public Object invoke(Invocation invocation) throws Throwable {
        OrderBean orderBean =  (OrderBean)invocation.getParameter(0);
        orderBean.setId("OID101");
        return null;
    }

    @Override
    public void describeTo(Description description) {
        description.appendText("Updates the order id field");
    }
}
