### ISSUE TITLE
jmock doesnt work with jdk8

### ISSUE THREAD

**Issue by raoofm** [jmock-developers/jmock-library#80]
Compilation error:
The method postForEntity(String, Object, Class<T>, Object...) in the type RestOperations is not applicable for the arguments (String, MultiValueMap, Class, Object[])

on code line:
oneOf(restOperations).postForEntity(with(equal(webserviceUrl)), with(any(MultiValueMap.class)), with((Class)null), with(new Object[]{}));

**Comment by raoofmd** [comment]
this works if we do below

oneOf(restOperations).postForEntity(with(equal(webserviceUrl)), with(any(MultiValueMap.class)), with((Class**<?>**)null), with(new Object[]{}));

**Comment by olibye** [comment]
The type signature is:-
`<T> ResponseEntity<T> postForEntity(String url, Object request, Class<T> responseType, Object... uriVariables)
			throws RestClientException;
`
Class is generic and should be parametrised with a type.
