### ISSUE TITLE
Can't build signed JAR because no ant buildfile

### ISSUE THREAD

**Issue by jbrains** [jmock-developers/jmock-library#88]
I would like to contribute, but it's unclear whether I can:

    $ mvn test
    Failed tests: 
        JavaReflectionImposteriserTests.testCanImposteriseAClassInASignedJarFile:64 Signed JAR file does not exist (use Ant to build it)
    $ ant
    Buildfile: build.xml does not exist!
    Build failed

Help?

**Comment by jbrains** [comment]
I think I figured this out, and I've submitted a pull request based on what I think I learned.

**Comment by olibye** [comment]
There's no ant file. The error message is incorrect. Maven builds the signed jar when the whole parent project is built, as per the Travis build.

**Comment by jbrains** [comment]
Yes. I have worked around this with `mvn package && mvn test`. Is there a more direct/clearer way to achieve the same result?

**Comment by olibye** [comment]
mvn clean install works for me, isn't this what everybody does?
