### ISSUE TITLE
History of API changes for JMock 2 Core

### ISSUE THREAD

**Issue by lvc** [jmock-developers/jmock-library#99]
Hi,

I'd like to share report on API changes and backward compatibility for the JMock 2 Core library: https://abi-laboratory.pro/java/tracker/timeline/jmock/

The report is generated by the https://github.com/lvc/japi-tracker tool according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Hope it will be helpful for users and maintainers of the library.

Thank you.

![jmock-1](https://user-images.githubusercontent.com/1517837/32208613-9faffe8c-be14-11e7-94f1-5326d0a43236.png)

![jmock-2](https://user-images.githubusercontent.com/1517837/32208612-9f918916-be14-11e7-8e24-b4aa6c3578f4.png)

**Comment by olibye** [comment]
Interesting thanks
